POST http://localhost:8081/orders
Content-Type: application/json

{
  "userId": "999fa683-765b-4fd2-8ef9-9a95c231e549",
  "restaurantId": "d215b5f8-0249-4dc5-89a3-51fd148cfb45",
  "address": {
    "street": "street_1",
    "postalCode": "1000AB",
    "city": "Amsterdam"
  },
  "price": 2500.00,
  "items": [
    {
      "productId": "8cecc491-f942-41fb-a144-d3b020a12689",
      "quantity": 1,
      "price": 1000.00,
      "subTotal": 1000.0
    },
    {
      "productId": "cfd43ef2-6d84-4336-89ca-5f4e25127322",
      "quantity": 3,
      "price": 500.00,
      "subTotal": 1500.0
    }
  ]
}
